version: "3"

services:
  masq-compile-linux:
    environment:
      - BUILD_DIR=linux-x86-64
    build: compile-linux
    image: masq-compile-linux
    volumes:
      - ./builds:/home/node/builds
      - .cargo/registry:/home/node/.cargo/registry
      - ./scripts/compile.sh:/home/node/compile.sh
  masq-run-node:
    environment:
      - MASQ_CLANDESTINE_PORT=13579
      - DNS_SERVERS=1.0.0.1,1.1.1.1,8.8.8.8,9.9.9.9
      - INFURA_ID=f29dff1a240b4583aad2f2c72d372dc0
      - EARNING_WALLET=0x27d9A2AC83b493f88ce9B4532EDcf74e95B9788d
    ports:
      - "13579:13579"
    build:
      context: .
      dockerfile: run-node/Dockerfile
    image: masq-run-node
    volumes:
      - ./builds/linux-x86-64:/usr/local/bin/
      - ./run-node/config.toml:/home/node/config.toml
      - ./run-node/helper.py:/home/node/helper.py
  masq-compile-pi:
    environment:
      - BUILD_DIR=rpi-arm6
    build: compile-pi
    image: masq-compile-pi
    volumes:
      - ./builds:/home/node/builds
      - .cargo/registry:/home/node/.cargo/registry
      - ./scripts/compile.sh:/home/node/compile.sh
